// AUTO-GENERATED by vibesentinel-trainer. DO NOT EDIT MANUALLY.
// Regenerate: cargo run -p vibesentinel-trainer -- --data data/normal_vibration.csv
//
// NOTE: Architecture changed from 20→10→4→10→20 to 26→13→6→13→26.
// These weights are PLACEHOLDERS (zeros). You MUST retrain:
//   cargo run -p vibesentinel-trainer

use vibesentinel_features::{
    INPUT_DIM, HIDDEN1_DIM, LATENT_DIM, HIDDEN2_DIM, OUTPUT_DIM, FEATURE_DIM,
};

pub const ANOMALY_THRESHOLD: f32 = 1.0f32;

pub const FEATURE_MEAN: [f32; FEATURE_DIM] = [0.0f32; FEATURE_DIM];
pub const FEATURE_STD: [f32; FEATURE_DIM] = [1.0f32; FEATURE_DIM];

/// Train to regenerate. Set to 0 to skip parity test.
pub const GOLDEN_FEATURE_COUNT: usize = 0;

pub const GOLDEN_INPUTS: [[f32; FEATURE_DIM]; 0] = [];
pub const GOLDEN_RECONSTRUCTIONS: [[f32; FEATURE_DIM]; 0] = [];

/// Encoder layer 1: INPUT_DIM → HIDDEN1_DIM
pub const W_ENC1: [[f32; INPUT_DIM]; HIDDEN1_DIM] = [[0.0f32; INPUT_DIM]; HIDDEN1_DIM];
pub const B_ENC1: [f32; HIDDEN1_DIM] = [0.0f32; HIDDEN1_DIM];

/// Encoder layer 2: HIDDEN1_DIM → LATENT_DIM
pub const W_ENC2: [[f32; HIDDEN1_DIM]; LATENT_DIM] = [[0.0f32; HIDDEN1_DIM]; LATENT_DIM];
pub const B_ENC2: [f32; LATENT_DIM] = [0.0f32; LATENT_DIM];

/// Decoder layer 1: LATENT_DIM → HIDDEN2_DIM
pub const W_DEC1: [[f32; LATENT_DIM]; HIDDEN2_DIM] = [[0.0f32; LATENT_DIM]; HIDDEN2_DIM];
pub const B_DEC1: [f32; HIDDEN2_DIM] = [0.0f32; HIDDEN2_DIM];

/// Decoder layer 2: HIDDEN2_DIM → OUTPUT_DIM
pub const W_DEC2: [[f32; HIDDEN2_DIM]; OUTPUT_DIM] = [[0.0f32; HIDDEN2_DIM]; OUTPUT_DIM];
pub const B_DEC2: [f32; OUTPUT_DIM] = [0.0f32; OUTPUT_DIM];
