use std::io::Write;

pub fn export_weights(
    w_enc1: &[f32],
    b_enc1: &[f32],
    w_enc2: &[f32],
    b_enc2: &[f32],
    w_dec1: &[f32],
    b_dec1: &[f32],
    w_dec2: &[f32],
    b_dec2: &[f32],
    threshold:    f32,
    feature_mean: &[f32; 20],
    feature_std:  &[f32; 20],
    output_path:  &str,
) -> anyhow::Result<()> {
    let mut file = std::fs::File::create(output_path)?;
    writeln!(file, "// AUTO-GENERATED by vibesentinel-trainer. DO NOT EDIT MANUALLY.")?;
    writeln!(file, "// Regenerate: cargo run --bin trainer -- --data data/normal_vibration.csv")?;
    writeln!(file)?;

    writeln!(file, "pub const ANOMALY_THRESHOLD: f32 = {:.10}f32;", threshold)?;
    writeln!(file)?;

    write_f32_array(&mut file, "FEATURE_MEAN", feature_mean)?;
    write_f32_array(&mut file, "FEATURE_STD",  feature_std)?;

    write_weight_matrix(&mut file, "W_ENC1", w_enc1, 20, 10)?;
    write_bias_array(&mut file,    "B_ENC1", b_enc1)?;
    write_weight_matrix(&mut file, "W_ENC2", w_enc2, 10, 4)?;
    write_bias_array(&mut file,    "B_ENC2", b_enc2)?;
    write_weight_matrix(&mut file, "W_DEC1", w_dec1, 4, 10)?;
    write_bias_array(&mut file,    "B_DEC1", b_dec1)?;
    write_weight_matrix(&mut file, "W_DEC2", w_dec2, 10, 20)?;
    write_bias_array(&mut file,    "B_DEC2", b_dec2)?;

    Ok(())
}

fn write_weight_matrix(
    f: &mut impl Write,
    name: &str,
    data: &[f32],
    in_dim: usize,
    out_dim: usize,
) -> anyhow::Result<()> {
    writeln!(f, "pub const {}: [[f32; {}]; {}] = [", name, in_dim, out_dim)?;
    for row in data.chunks(in_dim) {
        write!(f, "    [")?;
        for (j, &val) in row.iter().enumerate() {
            if j > 0 { write!(f, ", ")?; }
            write!(f, "{:.10}f32", val)?;
        }
        writeln!(f, "],")?;
    }
    writeln!(f, "];")?;
    writeln!(f)?;
    Ok(())
}

fn write_bias_array(f: &mut impl Write, name: &str, data: &[f32]) -> anyhow::Result<()> {
    write!(f, "pub const {}: [f32; {}] = [", name, data.len())?;
    for (i, &val) in data.iter().enumerate() {
        if i > 0 { write!(f, ", ")?; }
        write!(f, "{:.10}f32", val)?;
    }
    writeln!(f, "];")?;
    writeln!(f)?;
    Ok(())
}

fn write_f32_array(f: &mut impl Write, name: &str, data: &[f32; 20]) -> anyhow::Result<()> {
    write!(f, "pub const {}: [f32; 20] = [", name)?;
    for (i, &val) in data.iter().enumerate() {
        if i > 0 { write!(f, ", ")?; }
        write!(f, "{:.10}f32", val)?;
    }
    writeln!(f, "];")?;
    writeln!(f)?;
    Ok(())
}
